Feat: implement unit test getAll()
CHUPITO-Org/BE-Chupito pull request #11
Opened 2023-06-14 21:45 UTC by kellyCSalazar

## Describe your changes
Create unit test getAll()

## Issue ticket number and link
https://trello.com/c/ovU3G2sE

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-06-14 23:36 UTC, jlora-mck commented on services/events.service.js
> +      }
Is data a promise ? if so can we explore not doing this and instead do a `promise.all` ?

2023-06-14 23:39 UTC, jlora-mck commented on tests/fixtures/event.mock.js
> +      events.push(this.generate(eventsData[i]))
can we use for .. of

2023-06-14 23:39 UTC, jlora-mck commented on tests/services/events.service.spec.js
> +test.skip('Create event', async t => {
is this ok ? skipping this test ?

2023-06-14 23:40 UTC, jlora-mck commented on tests/services/events.service.spec.js
> +test.skip('Get event', async t => {
why we are skipping test again ? if we need to skip test please add a comment to the PR or add an inline comment so we know

2023-06-14 23:57 UTC, jlora-mck requested changes
Left a couple comment, please address all fors in the PR if possible :D but in general great work!

2023-06-15 22:18 UTC, jose-sal-y-rosas reviewed
Leave a comment

2023-06-15 22:18 UTC, jose-sal-y-rosas commented on services/events.service.js
> +      }
@kellyCSalazar I think you can use toArray here instead of that for.

2023-06-20 16:37 UTC, anversa-pro approved these changes
Great work Kelly!

2023-06-20 16:37 UTC, kellyCSalazar commented on services/events.service.js
> +      }
Changed for toArray

2023-06-20 16:37 UTC, kellyCSalazar commented on tests/fixtures/event.mock.js
>      let event = {
Changed for const

2023-06-20 16:38 UTC, kellyCSalazar commented on tests/fixtures/event.mock.js
> +      events.push(this.generate(eventsData[i]))
Changed for .map()

2023-06-20 16:45 UTC, kellyCSalazar commented on tests/services/events.service.spec.js
> +test.skip('Get event', async t => {
The tests will be passed for the moment, they will be done as the respective endpoint is done

2023-06-20 16:51 UTC, FelipeLosada1996 commented on tests/services/events.service.spec.js
> +  console.log('EVENTSDATA', eventsData)
remove console.log

2023-06-20 17:05 UTC, kellyCSalazar commented on tests/services/events.service.spec.js
> +test.skip('Create event', async t => {
The tests will be passed for the moment, they will be done as the respective endpoint is done

2023-06-20 17:07 UTC, kellyCSalazar commented on tests/services/events.service.spec.js
> +  console.log('EVENTSDATA', eventsData)
Delete consolo.log

2023-06-20 17:09 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-06-20 17:12 UTC, FelipeLosada1996 approved these changes

2023-06-20 17:27 UTC, jlora-mck approved these changes

2023-06-20 18:04 UTC, merged