feat: implement token validation
CHUPITO-Org/BE-Chupito pull request #14
Opened 2023-06-22 21:20 UTC by anversa-pro

## Describe your changes
Use event/:id/attendees endpoint to reuse the token verification with firebase SDK 
![image](https://github.com/CHUPITO-Org/BE-Chupito/assets/85180677/02d74ebb-4b69-471f-b6a3-be5bd04f52e8)

## Issue ticket number and link
https://trello.com/c/5bkWDhuA
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-06-22 21:27 UTC, jlora-mck commented on providers/firebase-auth.application.js
> +account.client_x509_cert_url = process.env.AUTH_CLIENT_CERT_URL
DRY DRY DRY (dont repeat yourself)

i made this comment in other PR, please dont repeat yourself you can use spread operator

`const account = {
...serviceAccount,
project_id = process.env.AUTH_PROJECT_ID,
.... //the rest
}`

2023-06-22 21:28 UTC, jlora-mck commented on providers/index.js
> +// const setupFirebaseAdminSDKApp = require('./firebase-admin.application')
remove comments please

2023-06-22 21:45 UTC, jose-sal-y-rosas requested changes
Please use current authentication file

2023-06-22 21:53 UTC, anversa-pro commented on providers/firebase-auth.application.js
> +account.client_x509_cert_url = process.env.AUTH_CLIENT_CERT_URL
Changes applied

2023-06-22 21:53 UTC, anversa-pro commented on providers/index.js
> +// const setupFirebaseAdminSDKApp = require('./firebase-admin.application')
Removed

2023-06-22 21:53 UTC, anversa-pro commented
> current authentication file in usage

2023-06-22 23:19 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-06-22 23:32 UTC, FelipeLosada1996 approved these changes

2023-06-23 13:54 UTC, jlora-mck approved these changes

2023-06-23 14:03 UTC, merged