feat: create image docker for backend
CHUPITO-Org/BE-Chupito pull request #21
Opened 2023-06-30 22:07 UTC by kellyCSalazar

## Describe your changes
Create image docker for backend

## Issue ticket number and link
https://trello.com/c/nJvEpg4O

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-06-30 22:11 UTC, SilviaTrujillano23 approved these changes

2023-06-30 22:14 UTC, anversa-pro approved these changes
Yay! habemus docker!!

2023-07-04 15:57 UTC, jose-sal-y-rosas requested changes
@kellyCSalazar please could you describe why yarn.lock was removed?
on the other hand, why a library or a helper is part of this PR?

2023-07-04 16:21 UTC, FelipeLosada1996 commented on helpers/utils.js
> +const isObjectEmpty = data => (Object.entries(data).length === 0 ? true : false)
This file isn't corresponding to this MR, and was already added

2023-07-04 17:11 UTC, kellyCSalazar commented
Those changes were from the previous pr, both the yarn and the helpers folder.
A rebase was made to fix it

2023-07-04 17:11 UTC, kellyCSalazar commented on helpers/utils.js
> +const isObjectEmpty = data => (Object.entries(data).length === 0 ? true : false)
Those changes were from the previous pr, both the yarn and the helpers folder.
A rebase was made to fix it

2023-07-04 17:24 UTC, jlora-mck approved these changes

2023-07-04 18:59 UTC, FelipeLosada1996 approved these changes

2023-07-04 20:38 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-07-04 20:38 UTC, merged