feat: fix docker-compose files for bff and db
CHUPITO-Org/BE-Chupito pull request #59
Opened 2023-11-15 20:57 UTC by anversa-pro

## Conference App - Backend

## Issue ticket number and link
https://trello.com/c/R0qN4dDw

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [x] :sparkles: Feature
- [x] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

- Dockerized BFF and database (DB) services not connecting correctly.

## What is the new behavior?

- Updated docker-compose files to fix issues with the Dockerized BFF and DB services.
- Added a Docker volume for data persistence to avoid data loss when containers are restarted.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-11-15 21:11 UTC, FelipeLosada1996 approved these changes

2023-11-16 05:28 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-16 05:28 UTC, jose-sal-y-rosas commented on docker-compose.yml
> +      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
I think the content of this variable is missing? Where are they define?

2023-11-16 05:28 UTC, jose-sal-y-rosas commented on docker-compose.local.yml
> +      - MONGODB_URI=$MONGODB_URI_COMPOSE
Same here, what is the value for this variable and where is define?

2023-11-16 14:49 UTC, anversa-pro commented on docker-compose.yml
> +      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
I removed sensitive data and defined it in the .env and .env.local file.

2023-11-16 15:00 UTC, anversa-pro commented on docker-compose.local.yml
> +      - MONGODB_URI=$MONGODB_URI_COMPOSE
I removed sensitive data and defined it in the .env and .env.local file.

2023-11-16 15:21 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-11-16 15:27 UTC, merged