Sofia/feat/mongoose config
CHUPITO-Org/BE-Chupito pull request #66
Opened 2024-01-23 22:51 UTC by Sofiag8

## Conference App - Backend

## Issue ticket number and link

https://trello.com/c/Rjpv241H/327-agregar-configuración-mongoose

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [x] :sparkles: Feature
- [ ] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

Add @nestjs/mongoose and mongoose packages, set mongoose connection config to app module, @nestjs/testing for future environment setup and update star:dev script due to previous changes 

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2024-01-23 23:05 UTC, FelipeLosada1996 commented on src/app.module.ts
> +  imports: [ ConfigModule.forRoot(), MongooseModule.forRoot(process.env.MONGODB_URI as string)],
Create a file with variables, to utilize all you need, and call just the variable. https://www.linkedin.com/advice/1/how-do-you-keep-microservice-configurations-simple#:~:text=Centralized%20configuration%20allows%20you%20to,access%20control%20and%20security%20measures.

2024-01-24 16:06 UTC, Sofiag8 commented on src/app.module.ts
> +  imports: [ ConfigModule.forRoot(), MongooseModule.forRoot(process.env.MONGODB_URI as string)],
done

2024-01-24 16:18 UTC, Sofiag8 commented on src/configuration/credentials.ts
> +    host: process.env.DB_HOST,
done

2024-01-24 16:24 UTC, FelipeLosada1996 approved these changes

2024-01-25 17:02 UTC, jose-sal-y-rosas requested changes
Please review changes

2024-01-25 17:02 UTC, jose-sal-y-rosas commented on src/app.module.ts
> +    MongooseModule.forRoot(`mongodb://${credentials().MONGO.USER}:${credentials().MONGO.PASSWORD}@${credentials().MONGO.HOST}:${credentials().MONGO.PORT}/?authMechanism=DEFAULT`)
Are you calling 3 times the function: credentials?

2024-01-25 17:02 UTC, jose-sal-y-rosas commented on src/configuration/credentials.ts
> +  MONGO: {
there is a specific file to handle environment variables, please could you check infrastructure/environment an try to use it?

2024-01-25 19:48 UTC, jose-sal-y-rosas approved these changes
👍🏼

2024-01-25 19:55 UTC, merged