feat: create the event module (controller, service, dto, entiity)
CHUPITO-Org/BE-Chupito pull request #67
Opened 2024-01-25 01:10 UTC by kellyCSalazar

## Conference App - Backend

## Issue ticket number and link
https://trello.com/c/BwD1fS39

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

## Pull request type

Please check the type of change your PR introduces:

- [ ] :sparkles: Feature
- [ ] :bug: Bugfix
- [ ] :pencil2: Fixing typos
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :ok_hand: Updating due to code review suggest
- [ ] :rocket: Release: v
- [ ] :wrench: Add or update configuration files
- [ ] :hammer: Add or update development scripts
- [ ] :bricks: Infrastructure related changes

## What is the current module?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2024-01-25 16:58 UTC, Sofiag8 approved these changes

2024-01-25 17:08 UTC, AlejandraRochaOMcKinsey approved these changes
OK

2024-01-25 19:25 UTC, FelipeLosada1996 commented on src/modules/events/dto/create-event.dto.ts
> +  eventDate!: string
All this values are mandatory? optional? 
if is a date, you can use `@IsDate()`

2024-01-25 19:25 UTC, FelipeLosada1996 commented on src/modules/events/dto/response-create-event.dto.ts
> +  eventDate!: Date
Validate the library `class-validator` to add input conditions

2024-01-25 19:25 UTC, FelipeLosada1996 commented on src/modules/events/event.controller.ts
> +  private readonly logger = new Logger('EventController')
You can inject the logger, to define it in the module and received in the constructor. Is no good practice do one in controller and other in services

2024-01-25 19:25 UTC, FelipeLosada1996 commented on src/modules/events/event.entity.ts
> +  @Prop()
Define type of prop. Is required? has a default values? 
https://docs.nestjs.com/techniques/mongodb

2024-01-25 19:25 UTC, FelipeLosada1996 commented on src/modules/events/event.mapper.ts
> +      status: 'ACTIVE',
ACTIVE can be a constant, to reuse in other modules

2024-01-25 19:25 UTC, FelipeLosada1996 commented on src/modules/events/event.mapper.ts
> +      status: 'ACTIVE',
Event has a type? is a any? define their type

2024-01-25 21:54 UTC, kellyCSalazar commented on src/modules/events/dto/response-create-event.dto.ts
> +  eventDate!: Date
more validations have been added

2024-01-25 21:54 UTC, kellyCSalazar commented on src/modules/events/event.controller.ts
> +  private readonly logger = new Logger('EventController')
Added Logger to the module

2024-01-25 21:55 UTC, kellyCSalazar commented on src/modules/events/event.mapper.ts
> +      status: 'ACTIVE',
An enum class was created

2024-01-25 21:55 UTC, kellyCSalazar commented on src/modules/events/event.entity.ts
> +  @Prop()
Added more validations

2024-01-25 22:21 UTC, FelipeLosada1996 commented on src/modules/events/event.controller.ts
> +    return eventToCreate
Is not necessary create a variable that will be return after be assigned. It could be `return await this.eventService.create(event)`

2024-01-25 22:21 UTC, FelipeLosada1996 commented on src/modules/events/event.service.ts
> +    return eventToCreate
Is not necessary create a variable that will be return after be assigned

2024-01-26 14:45 UTC, FelipeLosada1996 approved these changes

2024-01-26 17:10 UTC, jose-sal-y-rosas requested changes
Please review feedback

2024-01-26 17:10 UTC, jose-sal-y-rosas commented on yarn.lock
I don't see a change in package.json. Please could you explain why this file is part of the PR?

2024-01-26 18:55 UTC, FelipeLosada1996 approved these changes

2024-01-26 19:47 UTC, jose-sal-y-rosas approved these changes
👍🏼

2024-01-26 21:38 UTC, jose-sal-y-rosas commented
/retest

2024-01-26 22:22 UTC, merged